### ISSUE TITLE
Option to override column schema type inferred from csv.

### ISSUE THREAD

**Issue by andyredhead** [domoritz/csv2parquet#73]
Hi,
I'd like to be able to override the schema type set for one or more numeric columns before the parquet file is written because the inferred schema types seem to always choose large types (such as Int64 or Float64) when smaller types (Uint16 or Float32) would suffice for my data sets.
I've had a go at a putting something together, it seems to work (though I am very much a beginner rust dev!).
If you'd like to take a look, the code is [in this fork](https://github.com/andyredhead/csv2parquet/blob/main/src/main.rs).
Cheers, Andy

**Comment by domoritz** [comment]
We discussed getting explicit schema input in https://github.com/domoritz/csv2parquet/issues/40#issuecomment-998313646. It would be super useful. 

It would be awesome if you could send a pull request. This code was also one of my early Rust projects so I'm a beginner myself. 

If you send a pull request, please also send them to the related projects ([json2parquet](https://github.com/domoritz/json2parquet), [csv2arrow](https://github.com/domoritz/csv2arrow), or [json2arrow](https://github.com/domoritz/json2arrow)). You could so that after an initial review here.

**Comment by andyredhead** [comment]
Just had a read through the "explicit schema" thread (I hadn't realised it might be relevant).

The approach I've been taking isn't really aligned with reading in a complete schema... instead it still uses the initial schema inference and then builds a new schema by either copying fields from the inferred schema or creating a new field when a type override is specified on the command line (also, I only specify changing the type on numerics, not other aspects such as nullability).

My assumption was that people would do a dry run, take a look at the inferred schema, "twiddle" whichever fields didn't look right by adding the override flag before running again.

To get something like #40 working, perhaps there would be an option to write an inferred schema to a local file (so people had something to get started with) and another option to read the schema from a file (using this schema for the builder and not doing the schema inference step). This sounds feasible and it looks like the Arrow schema struct has to_json and "from" (which takes json), which could be a starting point. I have no idea what the "from" method does by way of validation and reporting problems with the input file structure/data. All my current approach does is for each override, check:

- The specified column is present in the inferred schema
- The specified type is one of the pre-determined strings that maps to an arrow type

Opening up to take a whole schema potentially increases the complexity of reporting problems back to the user?

I haven't looked at the other projects you've linked to, though I guess they work in a similar manner so something similar might work for them too.

I'll have a go at putting a pull request together for what I've done so far anyway (haven't tried doing that before... :))

**Comment by andyredhead** [comment]
And with just a moments further thought "an option to write an inferred schema to a local file" is just the current "print schema" piped to a local file... ;)
(doh!)

**Comment by domoritz** [comment]
Thanks for looking into this. There are three basic operations one might want to do: leave as is, modify, or delete. I think having support for taking in a schema is the most flexible since one can do whatever they want. With tools like jq, we could even script schema overrides by getting the schema with a dry run, modifying it, and then constructing the parquet file with a second run of this tool. 

I agree it's not the most convenient way in all cases but a first step. We could then add a way to only override a column maybe by default adding in the json schema for that column. 

And yes, the other tools are very similar.

**Comment by andyredhead** [comment]
Pull request supplied.

**Comment by andyredhead** [comment]
It's good to see the schema feature released :)

I just noticed that the readme doesn't show the new option and (now I come to think of it) there isn't any extra info such as where to find valid values for the schema file.

Do you intend to add those or shall I put together a pull request?

**Comment by domoritz** [comment]
Ah, I forgot to update the readmes. Yes, that would be awesome. You can generate the usage description with csv2parquet -h. Can you send a pull request and also send pre for the other repos?

**Comment by andyredhead** [comment]
Done :)

The usage text is a cut n paste of running --help for each command.

**Comment by domoritz** [comment]
Thank you. I added a comment. Can you update the prs?

**Comment by andyredhead** [comment]
All looks good to me, I think we can close this issue?
